project:
  type: website
  output-dir: docs
  
website:
  title: "bayesTPC Tutorials"
  navbar:
    background:	"primary"
    foreground: "light"
    logo: "images/vblogoedit.png"
    left:
      - href: about.qmd
        text: About bayesTPC
      - href: startup.qmd
        text: Getting Started
      - href: intro.qmd
        text: Tutorials    
      - href: BT_temp.qmd
        text: Bluetongue Refit
      - href: team.qmd
        text: "Team"
    right:
      - icon: github
        href: https://github.com/VectorByteOrg/bayesTPC-tutorials
      - icon: twitter
        href: https://twitter.com/vectorbite_rcn
    search: TRUE

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true
    fig-align: center
    fig-width: 6       
    fig-height: 4.5    
    fig-format: png
    fig-cap-location: bottom

editor: source 
