---
title: "The bayesTPC package"
---

The [bayesTPC R package](https://github.com/johnwilliamsmithjr/bayesTPC) is for Bayesian fitting of Thermal Performance Curves (TPCs) to trait responses. The package is built using the [nimble language](https://r-nimble.org/) and machinery as the underlying engine for Markov Chain Monte Carlo (MCMC). Our main aims in releasing bayesTPC were to support the adoption of Bayesian approaches in thermal physiology, and to promote TPC fitting that adequately quantifies uncertainty.

A paper introducing the package was published [Methods in Ecology and Evolution](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.70004). This paper introduces much of the functionality of the package. The version of the package corresponding to the published paper is [available on Zenodo](https://zenodo.org/records/14269863). The current development version of the package is available through our [github repository](https://github.com/johnwilliamsmithjr/bayesTPC).

